language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g bower
  - bower install
  - npm install
after_success:
  "curl --ftp-create-dirs -T build/ -u beerevent\\beerforall:netcompany-123 ftp://waws-prod-am2-003.ftp.azurewebsites.windows.net/site/wwwroot/"